server:
    port: 8082
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ead-course
        username: postgres
        password: wasd
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob.non-contextual-creation: true
        properties:
            hibernate:
                show_sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/oauth2/jwks
                # opaque-token:
                #     introspection-uri: http://localhost:8080/oauth2/introspect
                #     client-id: course-api
                #     client-secret: 123

                 
ead:
    api:
        url: 
            authuser: 'http://localhost:8087'

# logging:
#     level:
#         org:
#             springframework: DEBUG
